# Generated by Django 2.0.7 on 2018-07-04 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elasticsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Annotation name', max_length=255)),
                ('es_document', models.TextField(blank=True, help_text='JSON object on which annotation will be given, for now just TextField')),
                ('public', models.BooleanField(default=False, help_text='Public state or not. By default is not public.')),
                ('comment', models.TextField(blank=True, help_text='Comment')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notation', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, help_text='Note/Comment')),
            ],
        ),
        migrations.CreateModel(
            name='EsDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('json_object', models.TextField(blank=True, help_text='JSON object on which annotation will be given')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esdocument', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Tag', related_name='annotation', to='elasticsearchapp.Category'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(help_text='The user who created current annotation', on_delete=django.db.models.deletion.CASCADE, related_name='states', to=settings.AUTH_USER_MODEL),
        ),
    ]
